# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Compoucher
email: your-email@example.com
environment : production
JEKYLL_ENV : production
description: "Compoucher, Zach McArtor silly digital products"
baseurl: "" # the subpath of your site, e.g. /blog
url: http://compoucher.com
production_url: http://compoucher.com
twitter_username: zmcartor
github_username:  zmcartor

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-analytics

jekyll_analytics:
  GoogleAnalytics:          
    id: UA-113909515-1
    anonymizeIp: false 
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
